### PR TITLE
Add support for optionally explaining why inapplicable provisioning profiles are not applicable. Partially fixes #58251.

### PR DESCRIPTION
**Pull request by rolfbjarne**
https://bugzilla.xamarin.com/show_bug.cgi?id=58251

### CODE REVIEW

**Comment by rolfbjarne** [comment]
This also need a companion change in xamarin-macios: https://github.com/rolfbjarne/xamarin-macios/commit/3055add2241735c55989ed8707bd843e27b3af8f (which will be PR'ed once this is accepted)

**Comment by rolfbjarne** [comment]
This also need a companion change in xamarin-macios: https://github.com/rolfbjarne/xamarin-macios/commit/3055add2241735c55989ed8707bd843e27b3af8f (which will be PR'ed once this is accepted)

**Comment by jstedfast** [comment]
What happens when the user has 1000's of profiles?

**Comment by rolfbjarne** [comment]
Nothing, unless he enables diagnostic build logs, in which case the build output will be *very* long. But I don't see a problem with that (diagnostic build logs are supposed to be very verbose).

**Pull request merged**
